
[bookshelves]
	#The number of blocks in the X-level that the enchanting table can detect chiseled bookshelves. Each 'row' can hold up to 96 books. If you have many enchantments, you may need to increase this value to provide more space.
	#Range: 1 ~ 8
	bookshelfSearchX = 2
	#The number of blocks in the Y-level that the enchanting table can detect chiseled bookshelves. Each 'row' can hold up to 96 books. If you have many enchantments, you may need to increase this value to provide more space.
	#Range: 1 ~ 8
	bookshelfSearchY = 3
	#The number of blocks in the Z-level that the enchanting table can detect chiseled bookshelves. Each 'row' can hold up to 96 books. If you have many enchantments, you may need to increase this value to provide more space.
	#Range: 1 ~ 8
	bookshelfSearchZ = 2

[ancientbooks]
	#If enabled, Ancient Books are no longer required to unlock enchantments at the enchanting table. Enchantments still cost experience and materials as usual.
	disableAncientBookRequirement = false

[enchantingtable]
	#Allow ancient books to be replicated in the enchanting table.
	allowReplicate = false
	#Allow ancient books to be transmuted in the enchanting table.
	allowTransmute = false
	#Allow enchantments to be removed in the enchanting table.
	allowEnchantmentRemoval = true
	#If enabled, enchantments that have not been found will have be obfuscated in the enchanting table.
	obfuscateLockedEnchantments = true

[enchantedbooks]
	#If enabled, vanilla enchanted books will spawn normally in loot tables such as chests.
	enableEnchantedBookLootTables = false
	#If enabled, vanilla enchanted books will appear in villager trades.
	#Note: You must /reload for changes to take effect for this option!
	enableEnchantedBookTrades = false

