import os
import shutil
import paths

def generateEmptyFiles(thing_list):
    for i in thing_list:
        a = i.split(":")
        intermediate = "main/resources/data/immersiveenchanting/enchantment_costs"
        the_path = f"{paths.test_modpack}/{paths.data}/{intermediate}/{a[0]}/{a[1]}.json"
        os.makedirs(os.path.dirname(the_path), exist_ok=True)
        with open(the_path, 'w') as file:
            file.write("{}")

if __name__ == "__main__":
    for i in set(["alexscaves:field_extension",
"alexscaves:crystallization",
"alexscaves:ferrous_haste",
"alexscaves:arrow_inducting",
"alexscaves:heavy_slam",
"alexscaves:swiftwood",
"alexscaves:bonking",
"alexscaves:dazing_sweep",
"alexscaves:plummeting_flight",
"alexscaves:herd_phalanx",
"alexscaves:chomping_spirit",
"alexscaves:energy_efficiency",
"alexscaves:solar",
"alexscaves:x_ray",
"alexscaves:gamma_ray",
"alexscaves:second_wave",
"alexscaves:flinging",
"alexscaves:sea_swing",
"alexscaves:tsunami",
"alexscaves:charting_call",
"alexscaves:lasting_morale",
"alexscaves:taxing_bellow",
"alexscaves:enveloping_bubble",
"alexscaves:bouncing_bolt",
"alexscaves:seapairing",
"alexscaves:triple_splash",
"alexscaves:soak_seeking",
"alexscaves:detonating_death",
"alexscaves:rapid_possession",
"alexscaves:sightless",
"alexscaves:astral_transferring",
"alexscaves:impending_stab",
"alexscaves:sated_blade",
"alexscaves:double_stab",
"alexscaves:precise_volley",
"alexscaves:dark_nock",
"alexscaves:relentless_darkness",
"alexscaves:twilight_perfection",
"alexscaves:shaded_respite",
"alexscaves:targeted_ricochet",
"alexscaves:triple_split",
"alexscaves:bouncy_ball",
"alexscaves:explosive_flavor",
"alexscaves:far_flung",
"alexscaves:sharp_cane",
"alexscaves:straight_hook",
"alexscaves:spell_lasting",
"alexscaves:peppermint_punting",
"alexscaves:humungous_hex",
"alexscaves:multiple_mint",
"alexscaves:seekcandy"]).difference(["alexscaves:solar", 
            "alexscaves:field_extension",
            "alexscaves:crystallization",
            "alexscaves:ferrous_haste",
            "alexscaves:energy_efficiency",
            "alexscaves:second_wave",
            "alexscaves:flinging",
            "alexscaves:sea_swing",
            "alexscaves:tsunami",
            "alexscaves:x_ray",
            "alexscaves:gamma_ray",
            "alexscaves:bonking", 
            "alexscaves:swiftwood", 
            "alexscaves:dazing_sweep", 
            "alexscaves:solar", 
            "alexscaves:energy_efficiency", 
            "alexscaves:gamma_ray", 
            "alexscaves:shaded_respite", 
            "alexscaves:dark_nock", 
            "alexscaves:seapairing", 
            "alexscaves:taxing_bellow", 
            "alexscaves:charting_call", 
            "alexscaves:lasting_morale", 
            "alexscaves:enveloping_bubble", 
            "alexscaves:bouncing_bolt", 
            "alexscaves:soak_seeking", 
            "alexscaves:triple_splash", 
            "alexscaves:seapairing", 
            "alexscaves:humungous_hex", 
            "alexscaves:multiple_mint", 
            "alexscaves:spell_lasting", 
            "alexscaves:detonating_death", 
            "alexscaves:rapid_possession", 
            "alexscaves:sightless", 
            "alexscaves:arrow_inducting", 
            "alexscaves:heavy_slam",
            "alexscaves:astral_transferring"]): 
        print(i)

